#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
    pyResToolbox - A collection of Reservoir Engineering Utilities
              Copyright (C) 2022, Mark Burgoyne

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    The GNU General Public License can be found in the LICENSE directory,
    and at  <https://www.gnu.org/licenses/>.

          Contact author at mark.w.burgoyne@gmail.com

Eclipse VFP table generation: VFPINJ (injection) and VFPPROD (production)
keyword tables via the nodal module VLP correlations.
"""

import warnings

import numpy as np

from pyrestoolbox.constants import (
    BAR_TO_PSI, PSI_TO_BAR,
    M_TO_FT, FT_TO_M,
    SM3_TO_MMSCF,
    STB_TO_SM3, SM3_TO_STB,
    SCF_PER_STB_TO_SM3_PER_SM3, SM3_PER_SM3_TO_SCF_PER_STB,
    STB_PER_MSCF_TO_SM3_PER_SM3, SM3_PER_SM3_TO_STB_PER_MSCF,
)
from pyrestoolbox.validate import validate_methods


def _vfp_units(unit_system, flo_type):
    """Shared unit labels for VFPINJ / VFPPROD comment headers."""
    is_metric = (unit_system == 'METRIC')
    p_unit = "barsa" if is_metric else "psia"
    depth_unit = "m" if is_metric else "ft"
    if flo_type == "GAS":
        flo_unit = "sm3/d" if is_metric else "Mscf/d"
    else:
        flo_unit = "sm3/d" if is_metric else "stb/d"
    return is_metric, p_unit, depth_unit, flo_unit


def _vfp_prologue(tool, desc_line, completion, datum_depth, depth_unit,
                  fluids_line, thp_values, flo_rates, p_unit, flo_unit,
                  extra_lines=()):
    """Shared comment-header prologue for VFPINJ / VFPPROD keyword strings."""
    lines = [f"-- Generated by pyResToolbox {tool}", desc_line]
    if completion is not None:
        lines.append(f"-- Completion: {len(completion.segments)} segment(s),"
                     f"  Total MD: {completion.total_md:.1f} ft,"
                     f"  Total TVD: {completion.total_tvd:.1f} ft")
        for i, seg in enumerate(completion.segments):
            lines.append(f"--   Segment {i+1}: MD={seg.md:.1f} ft,"
                         f"  ID={seg.id:.3f} in,"
                         f"  deviation={seg.deviation:.1f} deg,"
                         f"  roughness={seg.roughness:.4f} in")
        lines.append(f"-- Temperature: THT={completion.tht:.1f} degF,"
                     f"  BHT={completion.bht:.1f} degF")
    lines.append(f"-- Datum depth: {datum_depth:.1f} {depth_unit}")
    lines.append(fluids_line)
    lines.extend(extra_lines)
    lines.append(f"-- THP range: {min(thp_values):.1f} - {max(thp_values):.1f} {p_unit}")
    lines.append(f"-- Flow range: {min(flo_rates):.1f} - {max(flo_rates):.1f} {flo_unit}")
    return lines


def _rates_sm3d_to_field(rates, is_gas):
    """sm3/d -> Mscf/d (gas) or stb/d (liquid)."""
    if is_gas:
        return [r * SM3_TO_MMSCF * 1000.0 for r in rates]
    return [r * SM3_TO_STB for r in rates]


def _rates_field_to_sm3d(rates, is_gas):
    """Mscf/d (gas) or stb/d (liquid) -> sm3/d."""
    if is_gas:
        return [r / SM3_TO_MMSCF / 1000.0 for r in rates]
    return [r * STB_TO_SM3 for r in rates]


def _format_vfpinj(table_num, datum_depth, flo_type, flo_rates, thp_values, bhp_array,
                    vlpmethod='', completion=None, gsg=0.65, wsg=1.07,
                    unit_system='FIELD'):
    """Format Eclipse VFPINJ keyword string."""
    is_metric, p_unit, depth_unit, flo_unit = _vfp_units(unit_system, flo_type)

    vlp_name = vlpmethod.name if hasattr(vlpmethod, 'name') else str(vlpmethod)
    lines = _vfp_prologue(
        "make_vfpinj",
        f"-- Table: {table_num}  Flow type: {flo_type}  VLP method: {vlp_name}",
        completion, datum_depth, depth_unit,
        f"-- Fluids: Gas SG={gsg:.4f}, Water SG={wsg:.4f}",
        thp_values, flo_rates, p_unit, flo_unit)
    lines.append("--")
    lines.append("VFPINJ")
    lines.append(f"  {table_num}  {datum_depth:.5E}  {flo_type}  THP  {unit_system}  BHP /")
    lines.append("  " + "  ".join(f"{r:.5E}" for r in flo_rates) + " /")
    lines.append("  " + "  ".join(f"{t:.5E}" for t in thp_values) + " /")
    for it in range(len(thp_values)):
        bhps = bhp_array[it, :]
        bhp_str = "  ".join(f"{b:.5E}" for b in bhps)
        lines.append(f"  {it+1}  {bhp_str} /")
    return "\n".join(lines) + "\n"


def _format_vfpprod(table_num, datum_depth, flo_type, wfr_type, gfr_type,
                    flo_rates, thp_values, wfr_values, gfr_values, alq_values,
                    bhp_array, vlpmethod='', well_type='', completion=None,
                    gsg=0.65, wsg=1.07, api=45, pb=0, rsb=0,
                    unit_system='FIELD'):
    """Format Eclipse VFPPROD keyword string."""
    is_metric, p_unit, depth_unit, flo_unit = _vfp_units(unit_system, flo_type)
    if is_metric:
        wfr_unit = "sm3/sm3" if wfr_type == "WGR" else "fraction"
        gfr_unit = "sm3/sm3"  # Both OGR (gas wells) and GOR (oil wells) are sm3/sm3 in METRIC
        pb_unit = "barsa"
        rsb_unit = "sm3/sm3"
    else:
        wfr_unit = "stb/Mscf" if wfr_type == "WGR" else "fraction"
        gfr_unit = "stb/Mscf" if gfr_type == "OGR" else "Mscf/stb"
        pb_unit = "psia"
        rsb_unit = "scf/stb"

    extra_lines = []
    if well_type == 'oil' and (pb > 0 or rsb > 0):
        extra_lines.append(f"-- Oil PVT: Pb={pb:.1f} {pb_unit}, Rsb={rsb:.1f} {rsb_unit}")

    vlp_name = vlpmethod.name if hasattr(vlpmethod, 'name') else str(vlpmethod)
    lines = _vfp_prologue(
        "make_vfpprod",
        f"-- Table: {table_num}  Well type: {well_type}  VLP method: {vlp_name}",
        completion, datum_depth, depth_unit,
        f"-- Fluids: Gas SG={gsg:.4f}, Water SG={wsg:.4f}, API={api:.1f}",
        thp_values, flo_rates, p_unit, flo_unit,
        extra_lines=extra_lines)
    lines.append(f"-- {wfr_type} range: {min(wfr_values):.4g} - {max(wfr_values):.4g} {wfr_unit}")
    lines.append(f"-- {gfr_type} range: {min(gfr_values):.4g} - {max(gfr_values):.4g} {gfr_unit}")
    lines.append("--")
    lines.append("VFPPROD")
    lines.append(f"  {table_num}  {datum_depth:.5E}  {flo_type}  {wfr_type}  {gfr_type}"
                 f"  THP  ''  {unit_system}  BHP /")
    lines.append("  " + "  ".join(f"{r:.5E}" for r in flo_rates) + " /")
    lines.append("  " + "  ".join(f"{t:.5E}" for t in thp_values) + " /")
    lines.append("  " + "  ".join(f"{w:.5E}" for w in wfr_values) + " /")
    lines.append("  " + "  ".join(f"{g:.5E}" for g in gfr_values) + " /")
    lines.append("  " + "  ".join(f"{a:.5E}" for a in alq_values) + " /")
    # BHP records: iterate ALQ(outer) > GFR > WFR > THP(inner)
    nthp = len(thp_values)
    nwfr = len(wfr_values)
    ngfr = len(gfr_values)
    nalq = len(alq_values)
    for ia in range(nalq):
        for ig in range(ngfr):
            for iw in range(nwfr):
                for it in range(nthp):
                    bhps = bhp_array[it, iw, ig, ia, :]
                    bhp_str = "  ".join(f"{b:.5E}" for b in bhps)
                    lines.append(f"  {it+1}  {iw+1}  {ig+1}  {ia+1}  {bhp_str} /")
    return "\n".join(lines) + "\n"


def make_vfpinj(
    table_num: int,
    completion,
    flo_type: str = 'WAT',
    vlpmethod: str = 'WG',
    flo_rates: list = None,
    thp_values: list = None,
    gas_pvt=None,
    gsg: float = 0.65,
    wsg: float = 1.07,
    oil_pvt=None,
    pb: float = 0,
    rsb: float = 0,
    sgsp: float = 0.65,
    api: float = 35,
    datum_depth: float = 0,
    export: bool = False,
    filename: str = '',
    metric: bool = False,
) -> dict:
    """ Generates an Eclipse VFPINJ keyword table for injection wells.

        Computes BHP as a function of flow rate and tubing head pressure using
        the nodal module VLP correlations.

        table_num: Integer VFP table number (>= 1)
        completion: A nodal.Completion object describing the wellbore
        flo_type: Flow rate type - 'WAT' (water), 'GAS' (gas), or 'OIL' (oil)
        vlpmethod: VLP correlation - 'HB', 'WG', 'GRAY', or 'BB'
        flo_rates: List of flow rates in ascending order.
                   Units: stb/d (WAT/OIL) or Mscf/d (GAS) in field; sm3/d in metric. Default provided if None
        thp_values: List of tubing head pressures (psia / barsa) in ascending order. Default provided if None
        gas_pvt: Optional GasPVT object for gas injection
        gsg: Gas specific gravity. Default 0.65
        wsg: Water specific gravity. Default 1.07
        oil_pvt: Optional OilPVT object for oil injection
        pb: Bubble point pressure (psia / barsa). For oil injection
        rsb: Solution GOR at Pb (scf/stb / sm3/sm3). For oil injection
        sgsp: Separator gas SG. Default 0.65
        api: API gravity. Default 35
        datum_depth: Bottom hole datum depth (ft / m). Default = completion total TVD
        export: If True, writes an Eclipse VFP file. Default False
        filename: Custom output filename. Default: VFPINJ_{table_num}.VFP
        metric: If True, inputs/outputs use Eclipse METRIC units (barsa, sm3/d, m).
                If False (default), inputs/outputs use FIELD units (psia, stb/d, Mscf/d, ft).

        Returns: Dictionary with keys:
            table_num, datum_depth, flo_type, flo_rates, thp_values,
            bhp (2D numpy array shape NTHP x NFLO),
            n_failed, eclipse_string
    """
    from pyrestoolbox.nodal import fbhp as nodal_fbhp

    # Validation
    if not isinstance(table_num, int) or table_num < 1:
        raise ValueError(f"table_num must be a positive integer, got {table_num}")

    flo_type = flo_type.upper()
    if flo_type not in ('WAT', 'GAS', 'OIL'):
        raise ValueError(f"flo_type must be 'WAT', 'GAS', or 'OIL', got '{flo_type}'")

    vlpm = validate_methods(["vlpmethod"], [vlpmethod])
    is_gas = (flo_type == 'GAS')

    # --- Metric input conversion ---
    # Save original metric values for Eclipse string output
    if metric:
        metric_flo_rates = list(flo_rates) if flo_rates is not None else None
        metric_thp_values = list(thp_values) if thp_values is not None else None

        # Convert inputs to oilfield
        if flo_rates is not None:
            flo_rates = _rates_sm3d_to_field(flo_rates, is_gas)
        if thp_values is not None:
            thp_values = [t * BAR_TO_PSI for t in thp_values]
        if datum_depth > 0:
            datum_depth = datum_depth * M_TO_FT
        if pb > 0:
            pb = pb * BAR_TO_PSI
        if rsb > 0:
            rsb = rsb * SM3_PER_SM3_TO_SCF_PER_STB

    if datum_depth <= 0:
        datum_depth = completion.total_tvd

    # Defaults (in oilfield units)
    if flo_rates is None:
        if flo_type == 'GAS':
            flo_rates = [1000, 5000, 10000, 20000, 50000]
        else:
            flo_rates = [100, 500, 1000, 2000, 5000, 10000]
    if thp_values is None:
        thp_values = [100, 200, 500, 1000, 2000]

    flo_rates = list(flo_rates)
    thp_values = list(thp_values)

    if len(flo_rates) < 2:
        raise ValueError("flo_rates must contain at least 2 values")
    if len(thp_values) < 1:
        raise ValueError("thp_values must contain at least 1 value")

    # Compute BHP grid (in oilfield units)
    nflo = len(flo_rates)
    nthp = len(thp_values)
    bhp_array = np.zeros((nthp, nflo))
    n_failed = 0

    for it, thp in enumerate(thp_values):
        for iflo, flo in enumerate(flo_rates):
            try:
                if flo_type == 'GAS':
                    bhp_val = nodal_fbhp(
                        thp=thp, completion=completion,
                        vlpmethod=vlpm, well_type='gas',
                        gas_pvt=gas_pvt,
                        qg_mmscfd=flo / 1000.0, cgr=0, qw_bwpd=0,
                        wsg=wsg, gsg=gsg, injection=True)
                elif flo_type == 'WAT':
                    bhp_val = nodal_fbhp(
                        thp=thp, completion=completion,
                        vlpmethod=vlpm, well_type='oil',
                        qt_stbpd=flo, gor=0, wc=1.0,
                        wsg=wsg, gsg=gsg, injection=True,
                        pb=0, rsb=0, sgsp=sgsp, api=api)
                else:  # OIL
                    bhp_val = nodal_fbhp(
                        thp=thp, completion=completion,
                        vlpmethod=vlpm, well_type='oil',
                        oil_pvt=oil_pvt,
                        qt_stbpd=flo, gor=0, wc=0,
                        wsg=wsg, gsg=gsg, injection=True,
                        pb=pb, rsb=rsb, sgsp=sgsp, api=api)

                bhp_array[it, iflo] = bhp_val
            except (RuntimeError, ValueError, ZeroDivisionError):
                bhp_array[it, iflo] = 1e-6
                n_failed += 1

    if n_failed > 0:
        warnings.warn(f"{n_failed} of {nthp * nflo} VFPINJ BHP calculations failed")

    # --- Metric output conversion ---
    if metric:
        bhp_array = bhp_array * PSI_TO_BAR
        datum_depth_out = datum_depth * FT_TO_M

        # Use original metric values for Eclipse string, or convert oilfield defaults
        out_flo = metric_flo_rates if metric_flo_rates is not None \
            else _rates_field_to_sm3d(flo_rates, is_gas)
        out_thp = metric_thp_values if metric_thp_values is not None \
            else [t * PSI_TO_BAR for t in thp_values]

        eclipse_str = _format_vfpinj(table_num, datum_depth_out, flo_type,
                                      out_flo, out_thp, bhp_array,
                                      vlpmethod=vlpm, completion=completion,
                                      gsg=gsg, wsg=wsg, unit_system='METRIC')
        out_datum_depth = datum_depth_out
        out_flo_rates = out_flo
        out_thp_values = out_thp
    else:
        eclipse_str = _format_vfpinj(table_num, datum_depth, flo_type,
                                      flo_rates, thp_values, bhp_array,
                                      vlpmethod=vlpm, completion=completion,
                                      gsg=gsg, wsg=wsg, unit_system='FIELD')
        out_datum_depth = datum_depth
        out_flo_rates = flo_rates
        out_thp_values = thp_values

    if export:
        fname = filename if filename else f"VFPINJ_{table_num}.VFP"
        with open(fname, 'w') as f:
            f.write(eclipse_str)

    return {
        "table_num": table_num,
        "datum_depth": out_datum_depth,
        "flo_type": flo_type,
        "flo_rates": out_flo_rates,
        "thp_values": out_thp_values,
        "bhp": bhp_array,
        "n_failed": n_failed,
        "eclipse_string": eclipse_str,
    }


def make_vfpprod(
    table_num: int,
    completion,
    well_type: str = 'gas',
    vlpmethod: str = 'WG',
    flo_rates: list = None,
    thp_values: list = None,
    wfr_values: list = None,
    gfr_values: list = None,
    alq_values: list = None,
    gas_pvt=None,
    gsg: float = 0.65,
    oil_vis: float = 1.0,
    api: float = 45,
    pr: float = 0,
    oil_pvt=None,
    pb: float = 0,
    rsb: float = 0,
    sgsp: float = 0.65,
    wsg: float = 1.07,
    datum_depth: float = 0,
    export: bool = False,
    filename: str = '',
    metric: bool = False,
) -> dict:
    """ Generates an Eclipse VFPPROD keyword table for production wells.

        Computes BHP as a function of flow rate, tubing head pressure,
        water fraction, gas fraction, and artificial lift quantity using
        the nodal module VLP correlations.

        For gas wells (FIELD): FLO=GAS (Mscf/d), WFR=WGR (stb/Mscf), GFR=OGR (stb/Mscf)
        For oil wells (FIELD): FLO=OIL (stb/d), WFR=WCT (fraction), GFR=GOR (Mscf/stb)
        For gas wells (METRIC): FLO=GAS (sm3/d), WFR=WGR (sm3/sm3), GFR=OGR (sm3/sm3)
        For oil wells (METRIC): FLO=OIL (sm3/d), WFR=WCT (fraction), GFR=GOR (sm3/sm3)

        table_num: Integer VFP table number (>= 1)
        completion: A nodal.Completion object describing the wellbore
        well_type: 'gas' or 'oil'
        vlpmethod: VLP correlation - 'HB', 'WG', 'GRAY', or 'BB'
        flo_rates: List of flow rates in ascending order. Default provided if None
        thp_values: List of tubing head pressures (psia / barsa). Default provided if None
        wfr_values: List of water fraction values. Default provided if None
                    Gas wells: WGR in stb/Mscf (field) or sm3/sm3 (metric). Oil wells: WCT as fraction (0-1)
        gfr_values: List of gas fraction values. Default provided if None
                    Gas wells: OGR in stb/Mscf (field) or sm3/sm3 (metric). Oil wells: GOR in Mscf/stb (field) or sm3/sm3 (metric)
        alq_values: List of artificial lift values. Default [0]
        gas_pvt: Optional GasPVT object
        gsg: Gas specific gravity. Default 0.65
        oil_vis: Condensate viscosity (cP). Default 1.0
        api: API gravity (condensate for gas wells, oil for oil wells). Default 45
        pr: Reservoir pressure (psia / barsa) for condensate dropout model. 0 disables. Default 0
        oil_pvt: Optional OilPVT object for oil wells
        pb: Bubble point pressure (psia / barsa). Required for oil wells
        rsb: Solution GOR at Pb (scf/stb / sm3/sm3). Required for oil wells
        sgsp: Separator gas SG. Default 0.65
        wsg: Water specific gravity. Default 1.07
        datum_depth: Bottom hole datum depth (ft / m). Default = completion total TVD
        export: If True, writes an Eclipse VFP file. Default False
        filename: Custom output filename. Default: VFPPROD_{table_num}.VFP
        metric: If True, inputs/outputs use Eclipse METRIC units (barsa, sm3/d, m, sm3/sm3).
                If False (default), inputs/outputs use FIELD units (psia, stb/d, Mscf/d, ft).

        Returns: Dictionary with keys:
            table_num, datum_depth, well_type, flo_type, wfr_type, gfr_type,
            flo_rates, thp_values, wfr_values, gfr_values, alq_values,
            bhp (5D numpy array shape NTHP x NWFR x NGFR x NALQ x NFLO),
            n_failed, eclipse_string
    """
    from pyrestoolbox.nodal import fbhp as nodal_fbhp

    # Validation
    if not isinstance(table_num, int) or table_num < 1:
        raise ValueError(f"table_num must be a positive integer, got {table_num}")

    well_type = well_type.lower()
    if well_type not in ('gas', 'oil'):
        raise ValueError(f"well_type must be 'gas' or 'oil', got '{well_type}'")

    vlpm = validate_methods(["vlpmethod"], [vlpmethod])
    is_gas = (well_type == 'gas')

    # --- Metric input conversion ---
    # Save original metric values for Eclipse string output
    if metric:
        metric_flo_rates = list(flo_rates) if flo_rates is not None else None
        metric_thp_values = list(thp_values) if thp_values is not None else None
        metric_wfr_values = list(wfr_values) if wfr_values is not None else None
        metric_gfr_values = list(gfr_values) if gfr_values is not None else None
        metric_pb = pb
        metric_rsb = rsb

        # Convert inputs to oilfield
        if flo_rates is not None:
            flo_rates = _rates_sm3d_to_field(flo_rates, is_gas)
        if thp_values is not None:
            thp_values = [t * BAR_TO_PSI for t in thp_values]
        if wfr_values is not None:
            if well_type == 'gas':
                wfr_values = [w * SM3_PER_SM3_TO_STB_PER_MSCF for w in wfr_values]  # sm3/sm3 -> stb/Mscf
            # Oil wells: WCT is fraction, no conversion
        if gfr_values is not None:
            if well_type == 'gas':
                gfr_values = [g * SM3_PER_SM3_TO_STB_PER_MSCF for g in gfr_values]  # sm3/sm3 -> stb/Mscf
            else:
                gfr_values = [g * SM3_PER_SM3_TO_SCF_PER_STB / 1000.0 for g in gfr_values]  # sm3/sm3 -> Mscf/stb
        if datum_depth > 0:
            datum_depth = datum_depth * M_TO_FT
        if pr > 0:
            pr = pr * BAR_TO_PSI
        if pb > 0:
            pb = pb * BAR_TO_PSI
        if rsb > 0:
            rsb = rsb * SM3_PER_SM3_TO_SCF_PER_STB

    if datum_depth <= 0:
        datum_depth = completion.total_tvd

    # Defaults (in oilfield units)
    if flo_rates is None:
        flo_rates = [1000, 5000, 10000, 20000, 50000, 100000] if well_type == 'gas' \
                    else [100, 500, 1000, 2000, 5000, 10000]
    if thp_values is None:
        thp_values = [100, 200, 500, 1000, 2000]
    if wfr_values is None:
        wfr_values = [0, 0.001, 0.005, 0.01] if well_type == 'gas' else [0, 0.2, 0.5, 0.8]
    if gfr_values is None:
        gfr_values = [0, 0.01, 0.05, 0.1] if well_type == 'gas' else [0.2, 0.5, 1.0, 2.0]
    if alq_values is None:
        alq_values = [0]

    flo_rates = list(flo_rates)
    thp_values = list(thp_values)
    wfr_values = list(wfr_values)
    gfr_values = list(gfr_values)
    alq_values = list(alq_values)

    # Anchor ratios at zero where physically meaningful
    # WFR: zero water is valid for both gas (WGR=0) and oil (WCT=0) wells
    if 0 not in wfr_values:
        wfr_values.insert(0, 0)
    # GFR: zero condensate (OGR=0) is valid for gas wells only
    if well_type == 'gas' and 0 not in gfr_values:
        gfr_values.insert(0, 0)

    if len(flo_rates) < 2:
        raise ValueError("flo_rates must contain at least 2 values")

    # Validate WCT range for oil wells
    if well_type == 'oil':
        if any(w >= 1.0 for w in wfr_values):
            raise ValueError("WCT values must be less than 1.0 for oil production wells")

    # Type labels
    if well_type == 'gas':
        flo_type, wfr_type, gfr_type = 'GAS', 'WGR', 'OGR'
    else:
        flo_type, wfr_type, gfr_type = 'OIL', 'WCT', 'GOR'

    # Compute BHP grid (in oilfield units)
    nflo = len(flo_rates)
    nthp = len(thp_values)
    nwfr = len(wfr_values)
    ngfr = len(gfr_values)
    nalq = len(alq_values)
    total = nflo * nthp * nwfr * ngfr * nalq

    bhp_array = np.zeros((nthp, nwfr, ngfr, nalq, nflo))
    n_failed = 0

    for ia, alq in enumerate(alq_values):
        for ig, gfr in enumerate(gfr_values):
            for iw, wfr in enumerate(wfr_values):
                for it, thp in enumerate(thp_values):
                    for iflo, flo in enumerate(flo_rates):
                        try:
                            if well_type == 'gas':
                                qg_mmscfd = flo / 1000.0
                                qw_bwpd = wfr * flo  # WGR(stb/Mscf) * rate(Mscf/d)
                                cgr = gfr * 1000.0    # OGR(stb/Mscf) -> stb/MMscf
                                bhp_val = nodal_fbhp(
                                    thp=thp, completion=completion,
                                    vlpmethod=vlpm, well_type='gas',
                                    gas_pvt=gas_pvt,
                                    qg_mmscfd=qg_mmscfd, cgr=cgr,
                                    qw_bwpd=qw_bwpd, oil_vis=oil_vis,
                                    api=api, pr=pr, wsg=wsg, gsg=gsg)
                            else:
                                wct = wfr
                                gor_scf_stb = gfr * 1000.0
                                qt_stbpd = flo / (1.0 - wct) if wct > 0 else flo
                                bhp_val = nodal_fbhp(
                                    thp=thp, completion=completion,
                                    vlpmethod=vlpm, well_type='oil',
                                    oil_pvt=oil_pvt,
                                    qt_stbpd=qt_stbpd, gor=gor_scf_stb,
                                    wc=wct, wsg=wsg, gsg=gsg,
                                    pb=pb, rsb=rsb, sgsp=sgsp, api=api)

                            bhp_array[it, iw, ig, ia, iflo] = bhp_val
                        except (RuntimeError, ValueError, ZeroDivisionError):
                            bhp_array[it, iw, ig, ia, iflo] = 1e-6
                            n_failed += 1

    if n_failed > 0:
        warnings.warn(f"{n_failed} of {total} VFPPROD BHP calculations failed")

    # --- Metric output conversion ---
    if metric:
        bhp_array = bhp_array * PSI_TO_BAR
        datum_depth_out = datum_depth * FT_TO_M

        # Use original metric values for Eclipse string, or convert oilfield defaults
        out_flo = metric_flo_rates if metric_flo_rates is not None \
            else _rates_field_to_sm3d(flo_rates, is_gas)
        out_thp = metric_thp_values if metric_thp_values is not None \
            else [t * PSI_TO_BAR for t in thp_values]
        if metric_wfr_values is not None:
            out_wfr = metric_wfr_values
        else:
            if well_type == 'gas':
                out_wfr = [w * STB_PER_MSCF_TO_SM3_PER_SM3 for w in wfr_values]
            else:
                out_wfr = list(wfr_values)  # WCT fraction, no conversion
        if metric_gfr_values is not None:
            out_gfr = metric_gfr_values
        else:
            if well_type == 'gas':
                out_gfr = [g * STB_PER_MSCF_TO_SM3_PER_SM3 for g in gfr_values]
            else:
                out_gfr = [g * 1000.0 * SCF_PER_STB_TO_SM3_PER_SM3 for g in gfr_values]  # Mscf/stb -> sm3/sm3
        # Anchor at zero may have been inserted - ensure zero stays in metric output
        if 0 not in out_wfr:
            out_wfr.insert(0, 0)
        if well_type == 'gas' and 0 not in out_gfr:
            out_gfr.insert(0, 0)

        eclipse_str = _format_vfpprod(table_num, datum_depth_out, flo_type, wfr_type, gfr_type,
                                       out_flo, out_thp, out_wfr, out_gfr,
                                       alq_values, bhp_array,
                                       vlpmethod=vlpm, well_type=well_type,
                                       completion=completion,
                                       gsg=gsg, wsg=wsg, api=api,
                                       pb=metric_pb, rsb=metric_rsb,
                                       unit_system='METRIC')
        out_datum_depth = datum_depth_out
        out_flo_rates = out_flo
        out_thp_values = out_thp
        out_wfr_values = out_wfr
        out_gfr_values = out_gfr
    else:
        eclipse_str = _format_vfpprod(table_num, datum_depth, flo_type, wfr_type, gfr_type,
                                       flo_rates, thp_values, wfr_values, gfr_values,
                                       alq_values, bhp_array,
                                       vlpmethod=vlpm, well_type=well_type,
                                       completion=completion,
                                       gsg=gsg, wsg=wsg, api=api, pb=pb, rsb=rsb,
                                       unit_system='FIELD')
        out_datum_depth = datum_depth
        out_flo_rates = flo_rates
        out_thp_values = thp_values
        out_wfr_values = wfr_values
        out_gfr_values = gfr_values

    if export:
        fname = filename if filename else f"VFPPROD_{table_num}.VFP"
        with open(fname, 'w') as f:
            f.write(eclipse_str)

    return {
        "table_num": table_num,
        "datum_depth": out_datum_depth,
        "well_type": well_type,
        "flo_type": flo_type,
        "wfr_type": wfr_type,
        "gfr_type": gfr_type,
        "flo_rates": out_flo_rates,
        "thp_values": out_thp_values,
        "wfr_values": out_wfr_values,
        "gfr_values": out_gfr_values,
        "alq_values": alq_values,
        "bhp": bhp_array,
        "n_failed": n_failed,
        "eclipse_string": eclipse_str,
    }
