#!/usr/bin/python3
# -*- coding: utf-8 -*-

"""
    pyResToolbox - A collection of Reservoir Engineering Utilities
              Copyright (C) 2022, Mark Burgoyne

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    The GNU General Public License can be found in the LICENSE directory,
    and at  <https://www.gnu.org/licenses/>.

          Contact author at mark.w.burgoyne@gmail.com

Eclipse VFP table generation: VFPINJ (injection) and VFPPROD (production)
keyword tables via the nodal module VLP correlations.
"""

import warnings
from dataclasses import dataclass

import numpy as np

from pyrestoolbox.constants import (
    BAR_TO_PSI, PSI_TO_BAR,
    M_TO_FT, FT_TO_M,
    SM3_TO_MMSCF,
    STB_TO_SM3, SM3_TO_STB,
    SCF_PER_STB_TO_SM3_PER_SM3, SM3_PER_SM3_TO_SCF_PER_STB,
    STB_PER_MSCF_TO_SM3_PER_SM3, SM3_PER_SM3_TO_STB_PER_MSCF,
)
from pyrestoolbox.validate import validate_methods


def _vfp_units(unit_system, flo_type):
    """Shared unit labels for VFPINJ / VFPPROD comment headers."""
    is_metric = (unit_system == 'METRIC')
    p_unit = "barsa" if is_metric else "psia"
    depth_unit = "m" if is_metric else "ft"
    if flo_type == "GAS":
        flo_unit = "sm3/d" if is_metric else "Mscf/d"
    else:
        flo_unit = "sm3/d" if is_metric else "stb/d"
    return is_metric, p_unit, depth_unit, flo_unit


def _vfp_prologue(tool, desc_line, completion, datum_depth, depth_unit,
                  fluids_line, thp_values, flo_rates, p_unit, flo_unit,
                  extra_lines=()):
    """Shared comment-header prologue for VFPINJ / VFPPROD keyword strings."""
    lines = [f"-- Generated by pyResToolbox {tool}", desc_line]
    if completion is not None:
        lines.append(f"-- Completion: {len(completion.segments)} segment(s),"
                     f"  Total MD: {completion.total_md:.1f} ft,"
                     f"  Total TVD: {completion.total_tvd:.1f} ft")
        for i, seg in enumerate(completion.segments):
            lines.append(f"--   Segment {i+1}: MD={seg.md:.1f} ft,"
                         f"  ID={seg.id:.3f} in,"
                         f"  deviation={seg.deviation:.1f} deg,"
                         f"  roughness={seg.roughness:.4f} in")
        lines.append(f"-- Temperature: THT={completion.tht:.1f} degF,"
                     f"  BHT={completion.bht:.1f} degF")
    lines.append(f"-- Datum depth: {datum_depth:.1f} {depth_unit}")
    lines.append(fluids_line)
    lines.extend(extra_lines)
    lines.append(f"-- THP range: {min(thp_values):.1f} - {max(thp_values):.1f} {p_unit}")
    lines.append(f"-- Flow range: {min(flo_rates):.1f} - {max(flo_rates):.1f} {flo_unit}")
    return lines


def _rates_sm3d_to_field(rates, is_gas):
    """sm3/d -> Mscf/d (gas) or stb/d (liquid)."""
    if is_gas:
        return [r * SM3_TO_MMSCF * 1000.0 for r in rates]
    return [r * SM3_TO_STB for r in rates]


def _rates_field_to_sm3d(rates, is_gas):
    """Mscf/d (gas) or stb/d (liquid) -> sm3/d."""
    if is_gas:
        return [r / SM3_TO_MMSCF / 1000.0 for r in rates]
    return [r * STB_TO_SM3 for r in rates]


def _format_vfpinj(table_num, datum_depth, flo_type, flo_rates, thp_values, bhp_array,
                    vlpmethod='', completion=None, gsg=0.65, wsg=1.07,
                    unit_system='FIELD'):
    """Format Eclipse VFPINJ keyword string."""
    is_metric, p_unit, depth_unit, flo_unit = _vfp_units(unit_system, flo_type)

    vlp_name = vlpmethod.name if hasattr(vlpmethod, 'name') else str(vlpmethod)
    lines = _vfp_prologue(
        "make_vfpinj",
        f"-- Table: {table_num}  Flow type: {flo_type}  VLP method: {vlp_name}",
        completion, datum_depth, depth_unit,
        f"-- Fluids: Gas SG={gsg:.4f}, Water SG={wsg:.4f}",
        thp_values, flo_rates, p_unit, flo_unit)
    lines.append("--")
    lines.append("VFPINJ")
    lines.append(f"  {table_num}  {datum_depth:.5E}  {flo_type}  THP  {unit_system}  BHP /")
    lines.append("  " + "  ".join(f"{r:.5E}" for r in flo_rates) + " /")
    lines.append("  " + "  ".join(f"{t:.5E}" for t in thp_values) + " /")
    for it in range(len(thp_values)):
        bhps = bhp_array[it, :]
        bhp_str = "  ".join(f"{b:.5E}" for b in bhps)
        lines.append(f"  {it+1}  {bhp_str} /")
    return "\n".join(lines) + "\n"


def _format_vfpprod(table_num, datum_depth, flo_type, wfr_type, gfr_type,
                    flo_rates, thp_values, wfr_values, gfr_values, alq_values,
                    bhp_array, vlpmethod='', well_type='', completion=None,
                    gsg=0.65, wsg=1.07, api=45, pb=0, rsb=0,
                    unit_system='FIELD'):
    """Format Eclipse VFPPROD keyword string."""
    is_metric, p_unit, depth_unit, flo_unit = _vfp_units(unit_system, flo_type)
    if is_metric:
        wfr_unit = "sm3/sm3" if wfr_type == "WGR" else "fraction"
        gfr_unit = "sm3/sm3"  # Both OGR (gas wells) and GOR (oil wells) are sm3/sm3 in METRIC
        pb_unit = "barsa"
        rsb_unit = "sm3/sm3"
    else:
        wfr_unit = "stb/Mscf" if wfr_type == "WGR" else "fraction"
        gfr_unit = "stb/Mscf" if gfr_type == "OGR" else "Mscf/stb"
        pb_unit = "psia"
        rsb_unit = "scf/stb"

    extra_lines = []
    if well_type == 'oil' and (pb > 0 or rsb > 0):
        extra_lines.append(f"-- Oil PVT: Pb={pb:.1f} {pb_unit}, Rsb={rsb:.1f} {rsb_unit}")

    vlp_name = vlpmethod.name if hasattr(vlpmethod, 'name') else str(vlpmethod)
    lines = _vfp_prologue(
        "make_vfpprod",
        f"-- Table: {table_num}  Well type: {well_type}  VLP method: {vlp_name}",
        completion, datum_depth, depth_unit,
        f"-- Fluids: Gas SG={gsg:.4f}, Water SG={wsg:.4f}, API={api:.1f}",
        thp_values, flo_rates, p_unit, flo_unit,
        extra_lines=extra_lines)
    lines.append(f"-- {wfr_type} range: {min(wfr_values):.4g} - {max(wfr_values):.4g} {wfr_unit}")
    lines.append(f"-- {gfr_type} range: {min(gfr_values):.4g} - {max(gfr_values):.4g} {gfr_unit}")
    lines.append("--")
    lines.append("VFPPROD")
    lines.append(f"  {table_num}  {datum_depth:.5E}  {flo_type}  {wfr_type}  {gfr_type}"
                 f"  THP  ''  {unit_system}  BHP /")
    lines.append("  " + "  ".join(f"{r:.5E}" for r in flo_rates) + " /")
    lines.append("  " + "  ".join(f"{t:.5E}" for t in thp_values) + " /")
    lines.append("  " + "  ".join(f"{w:.5E}" for w in wfr_values) + " /")
    lines.append("  " + "  ".join(f"{g:.5E}" for g in gfr_values) + " /")
    lines.append("  " + "  ".join(f"{a:.5E}" for a in alq_values) + " /")
    # BHP records: iterate ALQ(outer) > GFR > WFR > THP(inner)
    nthp = len(thp_values)
    nwfr = len(wfr_values)
    ngfr = len(gfr_values)
    nalq = len(alq_values)
    for ia in range(nalq):
        for ig in range(ngfr):
            for iw in range(nwfr):
                for it in range(nthp):
                    bhps = bhp_array[it, iw, ig, ia, :]
                    bhp_str = "  ".join(f"{b:.5E}" for b in bhps)
                    lines.append(f"  {it+1}  {iw+1}  {ig+1}  {ia+1}  {bhp_str} /")
    return "\n".join(lines) + "\n"


def _validate_table_num(table_num):
    """VFP table numbers are 1-based integers."""
    if not isinstance(table_num, int) or table_num < 1:
        raise ValueError(f"table_num must be a positive integer, got {table_num}")


def _axis_out(original, oilfield_values, convert):
    """Axis values for a metric Eclipse string: echo what the caller passed if
    they passed anything, otherwise convert the oilfield defaults back."""
    return list(original) if original is not None else convert(oilfield_values)


def _export_vfp(export, filename, default_name, eclipse_str):
    """Write the keyword string to disk when export is requested."""
    if not export:
        return
    with open(filename if filename else default_name, "w") as f:
        f.write(eclipse_str)


def _sweep_vfpinj_bhp(completion, vlpm, flo_type, thp_values, flo_rates,
                      gas_pvt, oil_pvt, gsg, wsg, sgsp, api, pb, rsb):
    """BHP grid (NTHP x NFLO) in oilfield units, injection sense.

    Points the VLP march cannot solve are set to 1e-6 and counted, so a partly
    converged table is still usable rather than raising the whole call away.
    """
    from pyrestoolbox.nodal import fbhp as nodal_fbhp

    bhp_array = np.zeros((len(thp_values), len(flo_rates)))
    n_failed = 0
    for it, thp in enumerate(thp_values):
        for iflo, flo in enumerate(flo_rates):
            try:
                if flo_type == 'GAS':
                    bhp_val = nodal_fbhp(
                        thp=thp, completion=completion,
                        vlpmethod=vlpm, well_type='gas',
                        gas_pvt=gas_pvt,
                        qg_mmscfd=flo / 1000.0, cgr=0, qw_bwpd=0,
                        wsg=wsg, gsg=gsg, injection=True)
                elif flo_type == 'WAT':
                    bhp_val = nodal_fbhp(
                        thp=thp, completion=completion,
                        vlpmethod=vlpm, well_type='oil',
                        qt_stbpd=flo, gor=0, wc=1.0,
                        wsg=wsg, gsg=gsg, injection=True,
                        pb=0, rsb=0, sgsp=sgsp, api=api)
                else:  # OIL
                    bhp_val = nodal_fbhp(
                        thp=thp, completion=completion,
                        vlpmethod=vlpm, well_type='oil',
                        oil_pvt=oil_pvt,
                        qt_stbpd=flo, gor=0, wc=0,
                        wsg=wsg, gsg=gsg, injection=True,
                        pb=pb, rsb=rsb, sgsp=sgsp, api=api)
                bhp_array[it, iflo] = bhp_val
            except (RuntimeError, ValueError, ZeroDivisionError):
                bhp_array[it, iflo] = 1e-6
                n_failed += 1
    return bhp_array, n_failed


def _sweep_vfpprod_bhp(completion, vlpm, well_type, thp_values, wfr_values,
                       gfr_values, alq_values, flo_rates, gas_pvt, oil_pvt,
                       gsg, wsg, sgsp, api, oil_vis, pr, pb, rsb):
    """BHP grid (NTHP x NWFR x NGFR x NALQ x NFLO) in oilfield units.

    Same failure handling as the injection sweep: unsolved points become 1e-6
    and are counted.
    """
    from pyrestoolbox.nodal import fbhp as nodal_fbhp

    bhp_array = np.zeros((len(thp_values), len(wfr_values), len(gfr_values),
                          len(alq_values), len(flo_rates)))
    n_failed = 0
    for ia, alq in enumerate(alq_values):
        for ig, gfr in enumerate(gfr_values):
            for iw, wfr in enumerate(wfr_values):
                for it, thp in enumerate(thp_values):
                    for iflo, flo in enumerate(flo_rates):
                        try:
                            if well_type == 'gas':
                                bhp_val = nodal_fbhp(
                                    thp=thp, completion=completion,
                                    vlpmethod=vlpm, well_type='gas',
                                    gas_pvt=gas_pvt,
                                    qg_mmscfd=flo / 1000.0,
                                    cgr=gfr * 1000.0,       # OGR stb/Mscf -> stb/MMscf
                                    qw_bwpd=wfr * flo,      # WGR stb/Mscf * Mscf/d
                                    oil_vis=oil_vis,
                                    api=api, pr=pr, wsg=wsg, gsg=gsg)
                            else:
                                wct = wfr
                                bhp_val = nodal_fbhp(
                                    thp=thp, completion=completion,
                                    vlpmethod=vlpm, well_type='oil',
                                    oil_pvt=oil_pvt,
                                    qt_stbpd=flo / (1.0 - wct) if wct > 0 else flo,
                                    gor=gfr * 1000.0,
                                    wc=wct, wsg=wsg, gsg=gsg,
                                    pb=pb, rsb=rsb, sgsp=sgsp, api=api)
                            bhp_array[it, iw, ig, ia, iflo] = bhp_val
                        except (RuntimeError, ValueError, ZeroDivisionError):
                            bhp_array[it, iw, ig, ia, iflo] = 1e-6
                            n_failed += 1
    return bhp_array, n_failed


def make_vfpinj(
    table_num: int,
    completion,
    flo_type: str = 'WAT',
    vlpmethod: str = 'WG',
    flo_rates: list = None,
    thp_values: list = None,
    gas_pvt=None,
    gsg: float = 0.65,
    wsg: float = 1.07,
    oil_pvt=None,
    pb: float = 0,
    rsb: float = 0,
    sgsp: float = 0.65,
    api: float = 35,
    datum_depth: float = 0,
    export: bool = False,
    filename: str = '',
    metric: bool = False,
) -> dict:
    """ Generates an Eclipse VFPINJ keyword table for injection wells.

        Computes BHP as a function of flow rate and tubing head pressure using
        the nodal module VLP correlations.

        table_num: Integer VFP table number (>= 1)
        completion: A nodal.Completion object describing the wellbore
        flo_type: Flow rate type - 'WAT' (water), 'GAS' (gas), or 'OIL' (oil)
        vlpmethod: VLP correlation - 'HB', 'WG', 'GRAY', or 'BB'
        flo_rates: List of flow rates in ascending order.
                   Units: stb/d (WAT/OIL) or Mscf/d (GAS) in field; sm3/d in metric. Default provided if None
        thp_values: List of tubing head pressures (psia / barsa) in ascending order. Default provided if None
        gas_pvt: Optional GasPVT object for gas injection
        gsg: Gas specific gravity. Default 0.65
        wsg: Water specific gravity. Default 1.07
        oil_pvt: Optional OilPVT object for oil injection
        pb: Bubble point pressure (psia / barsa). For oil injection
        rsb: Solution GOR at Pb (scf/stb / sm3/sm3). For oil injection
        sgsp: Separator gas SG. Default 0.65
        api: API gravity. Default 35
        datum_depth: Bottom hole datum depth (ft / m). Default = completion total TVD
        export: If True, writes an Eclipse VFP file. Default False
        filename: Custom output filename. Default: VFPINJ_{table_num}.VFP
        metric: If True, inputs/outputs use Eclipse METRIC units (barsa, sm3/d, m).
                If False (default), inputs/outputs use FIELD units (psia, stb/d, Mscf/d, ft).

        Returns: Dictionary with keys:
            table_num, datum_depth, flo_type, flo_rates, thp_values,
            bhp (2D numpy array shape NTHP x NFLO),
            n_failed, eclipse_string
    """
    _validate_table_num(table_num)

    flo_type = flo_type.upper()
    if flo_type not in ('WAT', 'GAS', 'OIL'):
        raise ValueError(f"flo_type must be 'WAT', 'GAS', or 'OIL', got '{flo_type}'")

    vlpm = validate_methods(["vlpmethod"], [vlpmethod])
    is_gas = (flo_type == 'GAS')

    # Keep the caller's own metric values so the Eclipse string can echo them back
    original = {'flo': list(flo_rates) if flo_rates is not None else None,
                'thp': list(thp_values) if thp_values is not None else None}
    if metric:
        if flo_rates is not None:
            flo_rates = _rates_sm3d_to_field(flo_rates, is_gas)
        if thp_values is not None:
            thp_values = [t * BAR_TO_PSI for t in thp_values]
        if datum_depth > 0:
            datum_depth = datum_depth * M_TO_FT
        if pb > 0:
            pb = pb * BAR_TO_PSI
        if rsb > 0:
            rsb = rsb * SM3_PER_SM3_TO_SCF_PER_STB

    if datum_depth <= 0:
        datum_depth = completion.total_tvd

    # Axis defaults, in oilfield units
    if flo_rates is None:
        flo_rates = [1000, 5000, 10000, 20000, 50000] if flo_type == 'GAS' \
                    else [100, 500, 1000, 2000, 5000, 10000]
    if thp_values is None:
        thp_values = [100, 200, 500, 1000, 2000]

    flo_rates = list(flo_rates)
    thp_values = list(thp_values)

    if len(flo_rates) < 2:
        raise ValueError("flo_rates must contain at least 2 values")
    if len(thp_values) < 1:
        raise ValueError("thp_values must contain at least 1 value")

    bhp_array, n_failed = _sweep_vfpinj_bhp(
        completion, vlpm, flo_type, thp_values, flo_rates,
        gas_pvt, oil_pvt, gsg, wsg, sgsp, api, pb, rsb)

    if n_failed > 0:
        warnings.warn(f"{n_failed} of {len(thp_values) * len(flo_rates)} "
                      "VFPINJ BHP calculations failed")

    # --- Metric output conversion ---
    if metric:
        bhp_array = bhp_array * PSI_TO_BAR
        out_datum_depth = datum_depth * FT_TO_M
        out_flo_rates = _axis_out(original['flo'], flo_rates,
                                  lambda v: _rates_field_to_sm3d(v, is_gas))
        out_thp_values = _axis_out(original['thp'], thp_values,
                                   lambda v: [t * PSI_TO_BAR for t in v])
        unit_system = 'METRIC'
    else:
        out_datum_depth = datum_depth
        out_flo_rates = flo_rates
        out_thp_values = thp_values
        unit_system = 'FIELD'

    eclipse_str = _format_vfpinj(table_num, out_datum_depth, flo_type,
                                 out_flo_rates, out_thp_values, bhp_array,
                                 vlpmethod=vlpm, completion=completion,
                                 gsg=gsg, wsg=wsg, unit_system=unit_system)

    _export_vfp(export, filename, f"VFPINJ_{table_num}.VFP", eclipse_str)

    return {
        "table_num": table_num,
        "datum_depth": out_datum_depth,
        "flo_type": flo_type,
        "flo_rates": out_flo_rates,
        "thp_values": out_thp_values,
        "bhp": bhp_array,
        "n_failed": n_failed,
        "eclipse_string": eclipse_str,
    }


@dataclass
class _VfpProdAxes:
    """The five VFPPROD axes plus the scalars that travel with them."""
    flo: list
    thp: list
    wfr: list
    gfr: list
    alq: list
    datum_depth: float
    pr: float = 0.0
    pb: float = 0.0
    rsb: float = 0.0


def _vfpprod_default_axes(is_gas, flo_rates, thp_values, wfr_values, gfr_values,
                          alq_values):
    """Fill in any axis the caller left unset, in oilfield units.

    Kept apart from the unit conversion so the default ranges can be retuned
    without touching conversion factors.
    """
    if flo_rates is None:
        flo_rates = [1000, 5000, 10000, 20000, 50000, 100000] if is_gas \
                    else [100, 500, 1000, 2000, 5000, 10000]
    if thp_values is None:
        thp_values = [100, 200, 500, 1000, 2000]
    if wfr_values is None:
        wfr_values = [0, 0.001, 0.005, 0.01] if is_gas else [0, 0.2, 0.5, 0.8]
    if gfr_values is None:
        gfr_values = [0, 0.01, 0.05, 0.1] if is_gas else [0.2, 0.5, 1.0, 2.0]
    if alq_values is None:
        alq_values = [0]
    return flo_rates, thp_values, wfr_values, gfr_values, alq_values


def _vfpprod_axes_to_oilfield(well_type, metric, completion, flo_rates, thp_values,
                              wfr_values, gfr_values, alq_values, datum_depth,
                              pr, pb, rsb):
    """Axes in oilfield units with defaults applied and zero anchors inserted.

    Also returns the caller's own values, so a METRIC Eclipse string can echo
    exactly what was passed in rather than a round-tripped version of it.
    """
    is_gas = (well_type == 'gas')
    original = {'flo': list(flo_rates) if flo_rates is not None else None,
                'thp': list(thp_values) if thp_values is not None else None,
                'wfr': list(wfr_values) if wfr_values is not None else None,
                'gfr': list(gfr_values) if gfr_values is not None else None,
                'pb': pb, 'rsb': rsb}

    if metric:
        if flo_rates is not None:
            flo_rates = _rates_sm3d_to_field(flo_rates, is_gas)
        if thp_values is not None:
            thp_values = [t * BAR_TO_PSI for t in thp_values]
        # Oil wells carry WFR as a water cut fraction, which needs no conversion
        if wfr_values is not None and is_gas:
            wfr_values = [w * SM3_PER_SM3_TO_STB_PER_MSCF for w in wfr_values]  # sm3/sm3 -> stb/Mscf
        if gfr_values is not None:
            if is_gas:
                gfr_values = [g * SM3_PER_SM3_TO_STB_PER_MSCF for g in gfr_values]  # sm3/sm3 -> stb/Mscf
            else:
                gfr_values = [g * SM3_PER_SM3_TO_SCF_PER_STB / 1000.0 for g in gfr_values]  # sm3/sm3 -> Mscf/stb
        if datum_depth > 0:
            datum_depth = datum_depth * M_TO_FT
        if pr > 0:
            pr = pr * BAR_TO_PSI
        if pb > 0:
            pb = pb * BAR_TO_PSI
        if rsb > 0:
            rsb = rsb * SM3_PER_SM3_TO_SCF_PER_STB

    if datum_depth <= 0:
        datum_depth = completion.total_tvd

    flo_rates, thp_values, wfr_values, gfr_values, alq_values = _vfpprod_default_axes(
        is_gas, flo_rates, thp_values, wfr_values, gfr_values, alq_values)

    axes = _VfpProdAxes(flo=list(flo_rates), thp=list(thp_values),
                        wfr=list(wfr_values), gfr=list(gfr_values),
                        alq=list(alq_values), datum_depth=datum_depth,
                        pr=pr, pb=pb, rsb=rsb)

    # Anchor ratios at zero where physically meaningful. WFR: zero water is valid
    # for both gas (WGR=0) and oil (WCT=0) wells. GFR: zero condensate (OGR=0) is
    # valid for gas wells only.
    if 0 not in axes.wfr:
        axes.wfr.insert(0, 0)
    if is_gas and 0 not in axes.gfr:
        axes.gfr.insert(0, 0)

    return axes, original


def _vfpprod_axes_to_metric(axes, original, well_type):
    """Axes back in the caller's METRIC units for the Eclipse string."""
    is_gas = (well_type == 'gas')
    if is_gas:
        wfr_back = lambda v: [w * STB_PER_MSCF_TO_SM3_PER_SM3 for w in v]
        gfr_back = lambda v: [g * STB_PER_MSCF_TO_SM3_PER_SM3 for g in v]
    else:
        wfr_back = list  # WCT is a fraction in both unit systems
        gfr_back = lambda v: [g * 1000.0 * SCF_PER_STB_TO_SM3_PER_SM3 for g in v]  # Mscf/stb -> sm3/sm3

    out = _VfpProdAxes(
        flo=_axis_out(original['flo'], axes.flo,
                      lambda v: _rates_field_to_sm3d(v, is_gas)),
        thp=_axis_out(original['thp'], axes.thp,
                      lambda v: [t * PSI_TO_BAR for t in v]),
        wfr=_axis_out(original['wfr'], axes.wfr, wfr_back),
        gfr=_axis_out(original['gfr'], axes.gfr, gfr_back),
        alq=list(axes.alq),
        datum_depth=axes.datum_depth * FT_TO_M,
        pr=axes.pr, pb=original['pb'], rsb=original['rsb'])

    # The zero anchor may have been inserted after the caller's values were saved
    if 0 not in out.wfr:
        out.wfr.insert(0, 0)
    if is_gas and 0 not in out.gfr:
        out.gfr.insert(0, 0)
    return out


def make_vfpprod(
    table_num: int,
    completion,
    well_type: str = 'gas',
    vlpmethod: str = 'WG',
    flo_rates: list = None,
    thp_values: list = None,
    wfr_values: list = None,
    gfr_values: list = None,
    alq_values: list = None,
    gas_pvt=None,
    gsg: float = 0.65,
    oil_vis: float = 1.0,
    api: float = 45,
    pr: float = 0,
    oil_pvt=None,
    pb: float = 0,
    rsb: float = 0,
    sgsp: float = 0.65,
    wsg: float = 1.07,
    datum_depth: float = 0,
    export: bool = False,
    filename: str = '',
    metric: bool = False,
) -> dict:
    """ Generates an Eclipse VFPPROD keyword table for production wells.

        Computes BHP as a function of flow rate, tubing head pressure,
        water fraction, gas fraction, and artificial lift quantity using
        the nodal module VLP correlations.

        For gas wells (FIELD): FLO=GAS (Mscf/d), WFR=WGR (stb/Mscf), GFR=OGR (stb/Mscf)
        For oil wells (FIELD): FLO=OIL (stb/d), WFR=WCT (fraction), GFR=GOR (Mscf/stb)
        For gas wells (METRIC): FLO=GAS (sm3/d), WFR=WGR (sm3/sm3), GFR=OGR (sm3/sm3)
        For oil wells (METRIC): FLO=OIL (sm3/d), WFR=WCT (fraction), GFR=GOR (sm3/sm3)

        table_num: Integer VFP table number (>= 1)
        completion: A nodal.Completion object describing the wellbore
        well_type: 'gas' or 'oil'
        vlpmethod: VLP correlation - 'HB', 'WG', 'GRAY', or 'BB'
        flo_rates: List of flow rates in ascending order. Default provided if None
        thp_values: List of tubing head pressures (psia / barsa). Default provided if None
        wfr_values: List of water fraction values. Default provided if None
                    Gas wells: WGR in stb/Mscf (field) or sm3/sm3 (metric). Oil wells: WCT as fraction (0-1)
        gfr_values: List of gas fraction values. Default provided if None
                    Gas wells: OGR in stb/Mscf (field) or sm3/sm3 (metric). Oil wells: GOR in Mscf/stb (field) or sm3/sm3 (metric)
        alq_values: List of artificial lift values. Default [0]
        gas_pvt: Optional GasPVT object
        gsg: Gas specific gravity. Default 0.65
        oil_vis: Condensate viscosity (cP). Default 1.0
        api: API gravity (condensate for gas wells, oil for oil wells). Default 45
        pr: Reservoir pressure (psia / barsa) for condensate dropout model. 0 disables. Default 0
        oil_pvt: Optional OilPVT object for oil wells
        pb: Bubble point pressure (psia / barsa). Required for oil wells
        rsb: Solution GOR at Pb (scf/stb / sm3/sm3). Required for oil wells
        sgsp: Separator gas SG. Default 0.65
        wsg: Water specific gravity. Default 1.07
        datum_depth: Bottom hole datum depth (ft / m). Default = completion total TVD
        export: If True, writes an Eclipse VFP file. Default False
        filename: Custom output filename. Default: VFPPROD_{table_num}.VFP
        metric: If True, inputs/outputs use Eclipse METRIC units (barsa, sm3/d, m, sm3/sm3).
                If False (default), inputs/outputs use FIELD units (psia, stb/d, Mscf/d, ft).

        Returns: Dictionary with keys:
            table_num, datum_depth, well_type, flo_type, wfr_type, gfr_type,
            flo_rates, thp_values, wfr_values, gfr_values, alq_values,
            bhp (5D numpy array shape NTHP x NWFR x NGFR x NALQ x NFLO),
            n_failed, eclipse_string
    """
    _validate_table_num(table_num)

    well_type = well_type.lower()
    if well_type not in ('gas', 'oil'):
        raise ValueError(f"well_type must be 'gas' or 'oil', got '{well_type}'")

    vlpm = validate_methods(["vlpmethod"], [vlpmethod])

    ax, original = _vfpprod_axes_to_oilfield(
        well_type, metric, completion, flo_rates, thp_values, wfr_values,
        gfr_values, alq_values, datum_depth, pr, pb, rsb)

    if len(ax.flo) < 2:
        raise ValueError("flo_rates must contain at least 2 values")
    if well_type == 'oil' and any(w >= 1.0 for w in ax.wfr):
        raise ValueError("WCT values must be less than 1.0 for oil production wells")

    if well_type == 'gas':
        flo_type, wfr_type, gfr_type = 'GAS', 'WGR', 'OGR'
    else:
        flo_type, wfr_type, gfr_type = 'OIL', 'WCT', 'GOR'

    bhp_array, n_failed = _sweep_vfpprod_bhp(
        completion, vlpm, well_type, ax.thp, ax.wfr, ax.gfr, ax.alq, ax.flo,
        gas_pvt, oil_pvt, gsg, wsg, sgsp, api, oil_vis, ax.pr, ax.pb, ax.rsb)

    if n_failed > 0:
        total = (len(ax.flo) * len(ax.thp) * len(ax.wfr)
                 * len(ax.gfr) * len(ax.alq))
        warnings.warn(f"{n_failed} of {total} VFPPROD BHP calculations failed")

    if metric:
        bhp_array = bhp_array * PSI_TO_BAR
        out = _vfpprod_axes_to_metric(ax, original, well_type)
        unit_system = 'METRIC'
    else:
        out = ax
        unit_system = 'FIELD'

    eclipse_str = _format_vfpprod(table_num, out.datum_depth, flo_type, wfr_type, gfr_type,
                                  out.flo, out.thp, out.wfr, out.gfr, out.alq, bhp_array,
                                  vlpmethod=vlpm, well_type=well_type,
                                  completion=completion,
                                  gsg=gsg, wsg=wsg, api=api, pb=out.pb, rsb=out.rsb,
                                  unit_system=unit_system)

    _export_vfp(export, filename, f"VFPPROD_{table_num}.VFP", eclipse_str)

    return {
        "table_num": table_num,
        "datum_depth": out.datum_depth,
        "well_type": well_type,
        "flo_type": flo_type,
        "wfr_type": wfr_type,
        "gfr_type": gfr_type,
        "flo_rates": out.flo,
        "thp_values": out.thp,
        "wfr_values": out.wfr,
        "gfr_values": out.gfr,
        "alq_values": out.alq,
        "bhp": bhp_array,
        "n_failed": n_failed,
        "eclipse_string": eclipse_str,
    }
