"""The delivered gas-free brine viscosity chain.

    mu = mu_water(IAPWS-2008) x salt ratio(ion-additive Jones-Dole)
         x pressure factor(Kestin)

GENERATED by brine_props/code/emit_port_tests.py - do not hand-edit the pinned
numbers. They are this repo's reference implementation's own output, so a
failure here means the port has drifted from it. Regenerate rather than patch.

Ported 2026-07-26. The chain is verified bit-identical to the reference
implementation over 2332 cases by brine_props/code/verify_port_viscosity.py.

WHAT IS AND IS NOT VALIDATED. The NaCl and KCl salt ratios are scored against
Kestin's measured viscosities (0.300%/0.78% and 0.764%/4.62% mean/max). Ion
MIXING is NOT validated against measurement - no measured mixed-brine viscosity
was found - so the multi-salt cases below pin agreement with PHREEQC, which is
verification of the implementation and not validation of the model.
"""
import math

import pytest

from pyrestoolbox.brine import viscosity_route as vr
from pyrestoolbox.brine import jones_dole_viscosity as jd
from pyrestoolbox.brine import kestin_nacl_viscosity as kestin



# Kestin (1981) Papers/50, his own printed tables (micro Pa s).
# (table, t_degC, p_MPa, m, printed mu)
KESTIN_TABLE_SPOTS = [
    (1, 20.0, 0.1, 0.0, 1002.0),
    (1, 25.0, 0.1, 0.0, 890.1),
    (1, 50.0, 10.0, 0.0, 548.9),
    (1, 100.0, 20.0, 0.0, 287.2),
    (1, 150.0, 35.0, 0.0, 190.7),
    (1, 75.0, 30.0, 0.0, 385.8),
    (7, 20.0, 0.1, 3.0, 1343.2),
    (7, 25.0, 0.1, 3.0, 1199.8),
    (7, 50.0, 10.0, 3.0, 758.7),
    (7, 100.0, 20.0, 3.0, 407.6),
    (7, 150.0, 35.0, 3.0, 273.5),
    (7, 75.0, 30.0, 3.0, 542.2),
    (13, 20.0, 0.1, 6.0, 1950.8),
    (13, 25.0, 0.1, 6.0, 1737.5),
    (13, 50.0, 10.0, 6.0, 1086.8),
    (13, 100.0, 20.0, 6.0, 574.1),
    (13, 150.0, 35.0, 6.0, 379.9),
    (13, 75.0, 30.0, 6.0, 769.9),
]


def test_kestin_reproduces_its_own_printed_tables():
    """The measured yardstick. `mu` returns micro Pa s, the paper's own unit.
    Worst deviation over the 18 printed values is 0.015%."""
    worst = 0.0
    for _tbl, t_C, p, m, printed in KESTIN_TABLE_SPOTS:
        worst = max(worst, abs(kestin.mu(t_C, p, m) - printed) / printed)
    assert worst < 2e-4, f"worst deviation {worst:.2e} from Kestin's own tables"



# PHREEQC 3.8.6 viscosity ratios (USER_PUNCH VISCOS/VISCOS_0).
# (t_degC, P_MPa, composition, mu/mu_0)
PHREEQC_RATIOS = [
    (25.0, 1.0, {'Na+': 1.0, 'Cl-': 1.0}, 1.09346),
    (25.0, 1.0, {'Na+': 5.0, 'Cl-': 5.0}, 1.722441),
    (100.0, 35.0, {'Na+': 3.0, 'Cl-': 3.0}, 1.426921),
    (150.0, 100.0, {'Na+': 6.0, 'Cl-': 6.0}, 1.979729),
    (60.0, 20.0, {'Na+': 2.0, 'Ca+2': 1.0, 'Cl-': 4.0}, 1.678617),
    (100.0, 50.0, {'Na+': 2.0, 'Mg+2': 1.0, 'Cl-': 4.0}, 1.791507),
    (25.0, 1.0, {'Na+': 3.0, 'Cl-': 1.0, 'SO4-2': 1.0}, 1.653332),
    (120.0, 35.0, {'Na+': 2.0, 'K+': 0.3, 'Mg+2': 0.8, 'Ca+2': 0.5, 'Cl-': 4.9}, 1.955956),
]


def test_reproduces_phreeqc_viscosity_ratios():
    """PHREEQC is the reference implementation of this salt model, so any
    disagreement is our bug rather than a difference of opinion."""
    worst = 0.0
    for t_C, P, comp, expect in PHREEQC_RATIOS:
        got = jd.viscosity_ratio(t_C + 273.15, P, comp)
        worst = max(worst, abs(got - expect) / expect)
    assert worst < 1e-4, f"worst deviation from PHREEQC {worst:.2e}"



# Delivered gas-free NaCl brine viscosity, mPa s (== cP).
# (T_K, P_MPa, molality, mu)
NACL_GRID = [
    (274.15, 0.1, 0.0, 1.731019453259371),
    (274.15, 0.1, 0.5, 1.7889732310783106),
    (274.15, 0.1, 2.0, 2.031067862206338),
    (274.15, 0.1, 5.0, 2.898278438031305),
    (274.15, 10.0, 0.0, 1.7116625936004988),
    (274.15, 10.0, 0.5, 1.7723012624453605),
    (274.15, 10.0, 2.0, 2.0206641553588436),
    (274.15, 10.0, 5.0, 2.8936020291241866),
    (274.15, 35.0, 0.0, 1.6708686070554337),
    (274.15, 35.0, 0.5, 1.7383938245806014),
    (274.15, 35.0, 2.0, 2.0032712121852247),
    (274.15, 35.0, 5.0, 2.893956921341702),
    (274.15, 100.0, 0.0, 1.611845482735292),
    (274.15, 100.0, 0.5, 1.6769111630836124),
    (274.15, 100.0, 2.0, 1.9323553532820914),
    (274.15, 100.0, 5.0, 2.7914872453212003),
    (298.15, 0.1, 0.0, 0.8900225512925751),
    (298.15, 0.1, 0.5, 0.9299526213646158),
    (298.15, 0.1, 2.0, 1.0764892281403113),
    (298.15, 0.1, 5.0, 1.532984884607608),
    (298.15, 10.0, 0.0, 0.8888088614925164),
    (298.15, 10.0, 0.5, 0.9301638188878563),
    (298.15, 10.0, 2.0, 1.080601313617422),
    (298.15, 10.0, 5.0, 1.543468920170019),
    (298.15, 35.0, 0.0, 0.8871948965660148),
    (298.15, 35.0, 0.5, 0.9322349804060682),
    (298.15, 35.0, 2.0, 1.0928204970777367),
    (298.15, 35.0, 5.0, 1.5726221050480997),
    (298.15, 100.0, 0.0, 0.8923593705927756),
    (298.15, 100.0, 0.5, 0.9376098703419745),
    (298.15, 100.0, 2.0, 1.099077091634923),
    (298.15, 100.0, 5.0, 1.5816090058973709),
    (323.15, 0.1, 0.0, 0.5465217288501752),
    (323.15, 0.1, 0.5, 0.5759907769417222),
    (323.15, 0.1, 2.0, 0.676062969643124),
    (323.15, 0.1, 5.0, 0.9585834975159689),
    (323.15, 10.0, 0.0, 0.5485385132401488),
    (323.15, 10.0, 0.5, 0.5784940900826364),
    (323.15, 10.0, 2.0, 0.6800189518924368),
    (323.15, 10.0, 5.0, 0.9654434547166404),
    (323.15, 35.0, 0.0, 0.5539262529746997),
    (323.15, 35.0, 0.5, 0.5851291820231181),
    (323.15, 35.0, 2.0, 0.6903833838988243),
    (323.15, 35.0, 5.0, 0.9833052610469563),
    (323.15, 100.0, 0.0, 0.5700737969781347),
    (323.15, 100.0, 0.5, 0.6021432932263535),
    (323.15, 100.0, 2.0, 0.7104222832431473),
    (323.15, 100.0, 5.0, 1.0118322506966555),
    (373.15, 0.1, 0.0, 0.2815846362545454),
    (373.15, 0.1, 0.5, 0.30031878268256296),
    (373.15, 0.1, 2.0, 0.3582518789164188),
    (373.15, 0.1, 5.0, 0.5022831812542241),
    (373.15, 10.0, 0.0, 0.28424636700349376),
    (373.15, 10.0, 0.5, 0.30311500490696963),
    (373.15, 10.0, 2.0, 0.3614838234413047),
    (373.15, 10.0, 5.0, 0.5066841635375117),
    (373.15, 35.0, 0.0, 0.2908713263128506),
    (373.15, 35.0, 0.5, 0.3100734545754437),
    (373.15, 35.0, 2.0, 0.369522752143056),
    (373.15, 35.0, 5.0, 0.5176256276972749),
    (373.15, 100.0, 0.0, 0.30771179320265546),
    (373.15, 100.0, 0.5, 0.32798467728638164),
    (373.15, 100.0, 2.0, 0.39083498244806664),
    (373.15, 100.0, 5.0, 0.547465038260972),
    (423.15, 0.1, 0.0, 0.18251408493112525),
    (423.15, 0.1, 0.5, 0.1962292035048058),
    (423.15, 0.1, 2.0, 0.23601124586046632),
    (423.15, 0.1, 5.0, 0.32722831990542933),
    (423.15, 10.0, 0.0, 0.18502181700998288),
    (423.15, 10.0, 0.5, 0.1987788390689611),
    (423.15, 10.0, 2.0, 0.2386795612691201),
    (423.15, 10.0, 5.0, 0.33037471386928663),
    (423.15, 35.0, 0.0, 0.1911493714624511),
    (423.15, 35.0, 0.5, 0.2049982542284976),
    (423.15, 35.0, 2.0, 0.2451570294763349),
    (423.15, 35.0, 5.0, 0.3379620975892177),
    (423.15, 100.0, 0.0, 0.20615019500227813),
    (423.15, 100.0, 0.5, 0.22103607675035952),
    (423.15, 100.0, 2.0, 0.2642971280499625),
    (423.15, 100.0, 5.0, 0.3643285680063779),
    (473.15, 0.1, 0.0, 0.13421437597382163),
    (473.15, 0.1, 0.5, 0.14525020118841508),
    (473.15, 0.1, 2.0, 0.17555271898449246),
    (473.15, 0.1, 5.0, 0.2411609899212277),
    (473.15, 10.0, 0.0, 0.136708588670808),
    (473.15, 10.0, 0.5, 0.147833489082466),
    (473.15, 10.0, 2.0, 0.17837184964732844),
    (473.15, 10.0, 5.0, 0.24462099247673896),
    (473.15, 35.0, 0.0, 0.14263616804157264),
    (473.15, 35.0, 0.5, 0.15395437529210532),
    (473.15, 35.0, 2.0, 0.18499742885013784),
    (473.15, 35.0, 5.0, 0.25266975018256643),
    (473.15, 100.0, 0.0, 0.15650952963583004),
    (473.15, 100.0, 0.5, 0.1688581445399947),
    (473.15, 100.0, 2.0, 0.20285090963189892),
    (473.15, 100.0, 5.0, 0.2770251506367172),
]


def test_nacl_grid_pinned_to_reference_implementation():
    for T, P, m, expect in NACL_GRID:
        got = vr.brine_viscosity(T, P, m=m)
        assert got == pytest.approx(expect, rel=1e-12), \
            f"T={T} P={P} m={m}: {got} != {expect}"



# Multi-salt. VERIFIED against PHREEQC, not validated against
# measurement - see the module docstring.
# (T_K, P_MPa, {salt: molality}, mu)
MULTISALT = [
    (298.15, 0.1, {'NaCl': 3.0}, 1.2036737733382623),
    (298.15, 0.1, {'KCl': 4.0}, 0.9381864554564822),
    (298.15, 0.1, {'NaCl': 2.0, 'CaCl2': 1.0}, 1.441367460018042),
    (298.15, 0.1, {'NaCl': 2.0, 'KCl': 0.3, 'MgCl2': 0.8, 'CaCl2': 0.5}, 1.690186245109653),
    (298.15, 0.1, {'CaBr2': 1.5}, 1.266631771384331),
    (298.15, 35.0, {'NaCl': 3.0}, 1.2284680167035407),
    (298.15, 35.0, {'KCl': 4.0}, 0.9607212462934256),
    (298.15, 35.0, {'NaCl': 2.0, 'CaCl2': 1.0}, 1.4785960438980772),
    (298.15, 35.0, {'NaCl': 2.0, 'KCl': 0.3, 'MgCl2': 0.8, 'CaCl2': 0.5}, 1.7348508193536216),
    (298.15, 35.0, {'CaBr2': 1.5}, 1.2919488904595486),
    (373.15, 0.1, {'NaCl': 3.0}, 0.40185502583196864),
    (373.15, 0.1, {'KCl': 4.0}, 0.3748878226765382),
    (373.15, 0.1, {'NaCl': 2.0, 'CaCl2': 1.0}, 0.47881734363902195),
    (373.15, 0.1, {'NaCl': 2.0, 'KCl': 0.3, 'MgCl2': 0.8, 'CaCl2': 0.5}, 0.5500264120720483),
    (373.15, 0.1, {'CaBr2': 1.5}, 0.4152274615983327),
    (373.15, 35.0, {'NaCl': 3.0}, 0.41431887381603943),
    (373.15, 35.0, {'KCl': 4.0}, 0.3864011452483977),
    (373.15, 35.0, {'NaCl': 2.0, 'CaCl2': 1.0}, 0.4934147741371514),
    (373.15, 35.0, {'NaCl': 2.0, 'KCl': 0.3, 'MgCl2': 0.8, 'CaCl2': 0.5}, 0.5667498839107545),
    (373.15, 35.0, {'CaBr2': 1.5}, 0.42634202141498917),
    (448.15, 0.1, {'NaCl': 3.0}, 0.22548494755805634),
    (448.15, 0.1, {'KCl': 4.0}, 0.22392311220705302),
    (448.15, 0.1, {'NaCl': 2.0, 'CaCl2': 1.0}, 0.265969174748611),
    (448.15, 0.1, {'NaCl': 2.0, 'KCl': 0.3, 'MgCl2': 0.8, 'CaCl2': 0.5}, 0.30378720757275246),
    (448.15, 0.1, {'CaBr2': 1.5}, 0.2098010388866895),
    (448.15, 35.0, {'NaCl': 3.0}, 0.2351844416154819),
    (448.15, 35.0, {'KCl': 4.0}, 0.23311444870177261),
    (448.15, 35.0, {'NaCl': 2.0, 'CaCl2': 1.0}, 0.2765107784831212),
    (448.15, 35.0, {'NaCl': 2.0, 'KCl': 0.3, 'MgCl2': 0.8, 'CaCl2': 0.5}, 0.31561231368882325),
    (448.15, 35.0, {'CaBr2': 1.5}, 0.22205353341879897),
]


def test_multisalt_pinned_to_reference_implementation():
    for T, P, salts, expect in MULTISALT:
        got = vr.brine_viscosity(T, P, salts=salts)
        assert got == pytest.approx(expect, rel=1e-12), \
            f"T={T} P={P} {salts}: {got} != {expect}"



S_THREE_MOLAL = 0.14917396703763816   # weight fraction NaCl == 3.0 mol/kg


def test_salinity_with_no_species_named_is_nacl():
    """The convention on both legs and every input form."""
    expect = 0.4125543932596675
    assert vr.brine_viscosity(373.15, 30.0, m=3.0) == pytest.approx(expect, rel=1e-12)
    assert vr.brine_viscosity(373.15, 30.0, salts={'NaCl': 3.0}) == pytest.approx(expect, rel=1e-12)
    assert vr.brine_viscosity(
        373.15, 30.0, composition={'Na+': 3.0, 'Cl-': 3.0}) == pytest.approx(expect, rel=1e-12)
    # and the weight-fraction form round-trips to the same molality
    assert vr.brine_viscosity(
        373.15, 30.0, S=S_THREE_MOLAL) == pytest.approx(expect, rel=1e-12)



def test_pressure_factor_is_clamped_not_extrapolated():
    """Kestin's box is 20-150 degC, 0.1-35 MPa, 6 molal. Above 35 MPa the factor
    is HELD, so the chain is pressure-blind from 35 to 100 MPa - a stated limit,
    not an accident."""
    comp = {'Na+': 3.0, 'Cl-': 3.0}
    at_35 = vr.pressure_factor(323.15, 35.0, comp)
    at_100 = vr.pressure_factor(323.15, 100.0, comp)
    assert at_35 == pytest.approx(1.0098860960056095, rel=1e-12)
    assert at_100 == pytest.approx(1.0098860960056095, rel=1e-12)
    assert at_100 == pytest.approx(at_35, rel=1e-12), "held, not extrapolated"
    # pure water carries no factor at all
    assert vr.pressure_factor(323.15, 100.0, {}) == 1.0


def test_superseded_route_refuses_what_it_cannot_represent():
    """Treating KCl as NaCl costs 15.9% mean / 51.2% max (Papers/51), so the
    NaCl-only route raises instead of silently doing it."""
    with pytest.raises(ValueError):
        vr.brine_viscosity(373.15, 30.0, salts={'KCl': 4.0}, route='mao_duan')
    # but it still serves an NaCl brine
    assert vr.brine_viscosity(373.15, 30.0, m=3.0, route='mao_duan') > 0.0


def test_exactly_one_salinity_input_is_required():
    with pytest.raises(ValueError):
        vr.brine_viscosity(373.15, 30.0, m=1.0, S=0.1)
    with pytest.raises(ValueError):
        vr.brine_viscosity(373.15, 30.0)


def test_unknown_route_raises():
    with pytest.raises(ValueError):
        vr.brine_viscosity(373.15, 30.0, m=1.0, route='not_a_route')


def test_viscosity_decreases_with_temperature_and_rises_with_salt():
    hot = vr.brine_viscosity(423.15, 30.0, m=1.0)
    cold = vr.brine_viscosity(323.15, 30.0, m=1.0)
    assert hot < cold
    fresh = vr.brine_viscosity(323.15, 30.0, m=0.0)
    briny = vr.brine_viscosity(323.15, 30.0, m=4.0)
    assert briny > fresh


def test_embedded_pitzer_table_is_not_read_from_disk():
    """A pip install has no PHREEQC. Passing database= must raise rather than
    silently reading a file that is not there."""
    with pytest.raises(ValueError):
        jd.viscosity_parameters(database='/nonexistent/pitzer.dat')

