"""
Appelo ion-additive apparent molar volumes - the MULTI-SALT brine leg.

Reference:
    Appelo, C.A.J., Parkhurst, D.L. and Post, V.E.A. (2014). "Equations for
    calculating hydrogeochemical reactions of minerals and gases such as CO2 at
    high pressures and temperatures." Geochim. Cosmochim. Acta 125, 49-67.
    DOI 10.1016/j.gca.2013.10.003   (Papers/47)
    Appelo, C.A.J. (2015). Appl. Geochem. 55, 62-71.
    DOI 10.1016/j.apgeochem.2014.11.007   (Papers/48)

WHY THIS ROUTE. It is the only one found that does multi-salt AND pressure AND
dissolved gases together. Krumgalz is 1 atm and stops at 95 degC; Rogers & Pitzer
is NaCl-only; Archer is not validatable. Appelo's stated range is 0-200 degC and
1-1000 atm, which covers this project's whole envelope (450 K vouched, 100 MPa).

Ion additivity is justified in Paper 47 rather than assumed here: "the volumes of
the individual ions in a mixture simply can be added to obtain the total volume of
the solutes, and hence the density of the solution" (Harned & Owen 1958; Ellis
1968; Millero 1972). That is the Young's-rule basis this front wanted.

MODEL - the HKFmoRR equation (Helgeson-Kirkham-Flowers-modified-Redlich-Rosenfeld),
Paper 47 Sec. 2.1, p. 53. Per ion i:

    Eq (6)  Vm_i  = V0m_i
                    + A_v * 0.5*z_i^2 * I^0.5 / (1 + a0_i * B_gamma * I^0.5)
                    + ( b1_i + b2_i/(T-228) + b3_i*(T-228) ) * I^b4_i

    Eq (7)  V0m_i = 41.84 * ( 0.1*a1_i
                              + 100*a2_i/(2600+P_bar)
                              + a3_i/(T-228)
                              + 1e4*a4_i/((2600+P_bar)*(T-228))
                              + w_i*1e5 * d(1/eps_r)/dP_bar )

`A_v` is the Debye-Huckel limiting slope for volume and comes from
**Bradley & Pitzer (1979)**, which Paper 47 cites and which this project already
implements and verifies (`bradley_pitzer_dielectric`). Confirmed to be the SAME
quantity, not merely similar: Appelo's Eq. (3) prefactor `A_gamma*(2/3)*2.303` =
0.7830 against our `2*A_phi` = 0.7828.

TWO THINGS PAPER 47 DOES NOT STATE, both pinned empirically against PHREEQC's own
`VM()` output (see `verify_ions()`), because guessing them would have been exactly
the failure this project keeps hitting:

  1. **The order of the ten `-Vm` numbers in `pitzer.dat`** is
     `a1 a2 a3 a4 omega a0 b1 b2 b3 b4`.
  2. **The omega term enters as `+omega*1e5*d(1/eps)/dP`**, i.e. the tabulated
     omega is scaled by 1e5 and carries the opposite sign to the minus printed in
     Eq. (7). With the printed sign the error is +4.41 cm3/mol on Cl-; with this
     one it is -0.0003. Both readings were scored; see `verify_ions()`.

Units: T in K, P in bar, m in mol/kg water, volumes in cm3/mol.
"""

import math

from ._lib_pitzer_params import CHARGE, DW, JD, MW, VM

from ._lib_dielectric import (dielectric_constant, dD_dP, A_V,
                                       N_AVOGADRO, E_CHARGE_ESU, K_BOLTZMANN)
from ..plyasunov.iapws_if97 import rho_if97

# ============================================================================
# Parameters, read from PHREEQC's pitzer.dat (public domain, USGS)
# ============================================================================


# Molar masses, g/mol, for the ions this leg supports.

def _species_name(reaction):
    """The species a SOLUTION_SPECIES reaction defines: its first product."""
    first = reaction.split('=', 1)[1].split('#')[0].split(' + ')[0].strip()
    parts = first.split()
    if len(parts) > 1 and re.fullmatch(r'\d+(\.\d+)?', parts[0]):
        first = ' '.join(parts[1:])
    return first


# ----------------------------------------------------------------------------
# PARAMETER SOURCE, and the one way the port differs from the research code.
# This repo's module parses PHREEQC's `pitzer.dat` on every call, which is right
# there because the file is the arbiter. A pip-installed library cannot: the
# user has no PHREEQC. The numbers are therefore EMBEDDED in
# `_lib_pitzer_params.py`, generated by brine_props/code/export_pitzer_params.py
# and verified bit-identical to a live parse. Passing `database=` raises rather
# than silently reading a file that is probably absent.
# ----------------------------------------------------------------------------

def load_vm_parameters(database=None):
    """The embedded `pitzer.dat` table. See the note above on `database=`."""
    if database is not None:
        raise ValueError(
            "database= is not supported in pyResToolbox: the pitzer.dat "
            "parameters are embedded (see _lib_pitzer_params.py, generated by "
            "brine_props/code/export_pitzer_params.py). Re-export that table "
            "instead of pointing at a file.")
    return VM


def parameters(database=None):
    return load_vm_parameters(database)


# ============================================================================
# The model
# ============================================================================

def d_inv_eps_dP(T_K, P_bar):
    """d(1/eps_r)/dP in 1/bar, from the Bradley & Pitzer dielectric equation."""
    D = dielectric_constant(T_K, P_bar)
    return -dD_dP(T_K, P_bar) / (D * D)


def B_gamma(T_K, P_bar, rho_w=None):
    """
    Debye-Huckel B (the reciprocal-length parameter) in 1/Angstrom.

    Derived from the same CGS constants as A_phi rather than taken from a
    remembered textbook value:
        B = sqrt(8*pi*N_A*e^2*rho_w / (1000*eps_r*k*T))   [1/cm]
    Reproduces the standard 0.3284 1/Angstrom at 25 degC, 1 bar.
    """
    if rho_w is None:
        rho_w = rho_if97(T_K, P_bar / 10.0) / 1000.0
    eps = dielectric_constant(T_K, P_bar)
    B_per_cm = math.sqrt(8.0 * math.pi * N_AVOGADRO * E_CHARGE_ESU ** 2 * rho_w
                         / (1000.0 * eps * K_BOLTZMANN * T_K))
    return B_per_cm / 1.0e8          # 1/cm -> 1/Angstrom


def V0_ion(species, T_K, P_bar, params=None):
    """Eq. (7): intrinsic (infinite-dilution) molar volume, cm3/mol."""
    p = (params or parameters())[species]
    a1, a2, a3, a4, omega = p[0], p[1], p[2], p[3], p[4]
    tt = T_K - 228.0
    return 41.84 * (0.1 * a1
                    + 100.0 * a2 / (2600.0 + P_bar)
                    + a3 / tt
                    + 1e4 * a4 / ((2600.0 + P_bar) * tt)
                    + omega * 1e5 * d_inv_eps_dP(T_K, P_bar))


def Vm_ion(species, T_K, P_bar, I, params=None, Av=None, Bg=None):
    """Eq. (6): apparent molar volume of one ion at ionic strength I, cm3/mol."""
    p = (params or parameters())[species]
    a0, b1, b2, b3, b4 = p[5], p[6], p[7], p[8], p[9]
    z = CHARGE.get(species, 0)

    v = V0_ion(species, T_K, P_bar, params)
    if I <= 0:
        return v

    if Av is None:
        Av = A_V(T_K, P_bar)
    if Bg is None:
        Bg = B_gamma(T_K, P_bar)

    sqrtI = math.sqrt(I)
    v += Av * 0.5 * z * z * sqrtI / (1.0 + a0 * Bg * sqrtI)
    tt = T_K - 228.0
    v += (b1 + b2 / tt + b3 * tt) * I ** b4
    return v


def ionic_strength(composition):
    """I = 0.5 * sum(m_i * z_i^2), mol/kg water."""
    return 0.5 * sum(m * CHARGE.get(s, 0) ** 2 for s, m in composition.items())


def brine_density(T_K, P_MPa, composition, params=None):
    """
    Gas-free brine density in kg/m3 from an ION composition.

    Parameters:
        composition: {species: molality}, e.g.
                     {'Na+': 5.0, 'Cl-': 5.0}
                     {'Na+': 1.8, 'K+': 0.2, 'Mg+2': 1.8, 'Ca+2': 0.47, 'Cl-': 6.7}

    The construction is additive over ions, which is what makes it multi-salt:
        V_solution = V_water + sum_i m_i * Vm_i
        mass       = 1000 g water + sum_i m_i * MW_i
    """
    P_bar = P_MPa * 10.0
    p = params or parameters()
    I = ionic_strength(composition)

    Av = A_V(T_K, P_bar)
    Bg = B_gamma(T_K, P_bar)

    rho_w = rho_if97(T_K, P_MPa)            # kg/m3
    V = 1e6 / rho_w                          # cm3 per 1 kg of water
    mass = 1000.0                            # g

    for s, m in composition.items():
        if m <= 0:
            continue
        V += m * Vm_ion(s, T_K, P_bar, I, p, Av, Bg)
        mass += m * MW[s]

    return mass / V * 1000.0                 # g/cm3 -> kg/m3


# ----------------------------------------------------------------------------
# Salinity input helpers, ported from brine_props `salt_route.ions_from_salts`
# and `brine_properties.molality_from_salinity` so the dispatcher can accept
# `salts={salt: molality}` and `S=<weight fraction>` as it does there.
# ----------------------------------------------------------------------------

# EXACTLY the eight salts brine_props `salt_route._SALT_IONS` accepts. Do not
# widen this here: the port must mirror the source, and a salt added on one side
# only is how the two drift.
_SALT_IONS = {
    'NaCl':  {'Na+': 1.0, 'Cl-': 1.0},
    'KCl':   {'K+': 1.0, 'Cl-': 1.0},
    'CaCl2': {'Ca+2': 1.0, 'Cl-': 2.0},
    'MgCl2': {'Mg+2': 1.0, 'Cl-': 2.0},
    'CaBr2': {'Ca+2': 1.0, 'Br-': 2.0},
    'Na2SO4': {'Na+': 2.0, 'SO4-2': 1.0},
    'SrCl2': {'Sr+2': 1.0, 'Cl-': 2.0},
    'BaCl2': {'Ba+2': 1.0, 'Cl-': 2.0},
}

M_NACL = 58.4428


def ions_from_salts(salts):
    """{salt: molality} -> {ion: molality}."""
    out = {}
    for salt, m in salts.items():
        if salt not in _SALT_IONS:
            raise ValueError(
                f"unknown salt {salt!r}; known: {sorted(_SALT_IONS)}")
        for ion, nu in _SALT_IONS[salt].items():
            out[ion] = out.get(ion, 0.0) + nu * m
    return out


def molality_from_salinity(S):
    """NaCl molality (mol/kg water) from weight fraction."""
    S = float(S)
    if S <= 0.0:
        return 0.0
    return S / ((1.0 - S) * M_NACL / 1000.0)
