"""Ion-additive brine viscosity: the modified Jones-Dole equation of PHREEQC.

Appelo & Parkhurst's viscosity model, implemented from scratch and dependency
free so it ports to Dart alongside the rest of the chain. Parameters are read
straight out of PHREEQC's `pitzer.dat` (public domain, USGS), where each ion
carries a `-viscosity` line.

WHY THIS EXISTS. The shipped salt viscosity term is Mao-Duan's NaCl-only ratio.
The volume leg went multi-salt in the seventeenth block (`appelo_volumes`), so
the viscosity leg is the remaining NaCl-only piece, and it is the larger error
of the two viscosity terms.

WHERE THE MODEL COMES FROM. `pitzer.dat`'s footer states the form and cites
"Appelo and Parkhurst in prep., for parameters see subroutine viscosity in
transport.cpp". The paper does not exist yet, so the REFERENCE IMPLEMENTATION
is the specification: PHREEQC 3.8.6 `src/transport.cpp`, `Phreeqc::viscosity`.
That is also the arbiter - `jones_dole_benchmark.py` scores this module against
PHREEQC's own output, so any disagreement is our bug rather than a difference
of opinion.

THE EQUATIONS, as coded in transport.cpp:

    mu/mu_0 = 1 + A*sqrt(eq/2/kg) / mu_0  +  fan * (sum_i B_i*m_i + D-terms)

    B_i  = b0 + b1*exp(-b2*tc)                          Jones_Dole[0..2]
    D_i  = d1*exp(-d2*tc)                               Jones_Dole[3,4]
    D-term_i = D_i * m_i * ( I^d3*(1 + fI) + (m_i*f_z)^d3 ) / (2 + fI)
    d3   = Jones_Dole[5],  f_z = (z^2 + |z|)/2
    fI   = I/3/d3  (d3 >= 1);  -0.8/d3  (0.4 < d3 < 1);  -1 otherwise
    fan  = 2 - V_an/V_Cl-,  the anion-volume correction (1 for pure chloride)
    A    = the Falkenhagen-Dole electrostatic term, built from the ion tracer
           diffusion coefficients (`-dw` in pitzer.dat) and the Bradley &
           Pitzer dielectric constant.

    tc is capped at 200 degC, as PHREEQC does.

THE WATER LEG IS IAPWS-2008. PHREEQC computes `viscos_0` from Huber et al.
(2009) - the same correlation as `iapws_viscosity`, which this project already
verified to <0.034 ppm against Huber's own Table 6. The A term scales with it,
so pairing this salt leg with the Mao-Duan water leg would not reproduce
PHREEQC.

CI- IS THE REFERENCE SOLUTE: its `-viscosity` line is all zeros, so in a pure
NaCl brine the B and D terms come from Na+ alone and `fan` is exactly 1.
"""

import math

from ._lib_pitzer_params import DW, JD
from .appelo_volumes import CHARGE, Vm_ion, ionic_strength, parameters
from ._lib_dielectric import dielectric_constant
from ..plyasunov.iapws_if97 import rho_if97
from .iapws_viscosity import mu_iapws2008


# PHREEQC's hard-coded reference value, transport.cpp: pure-water viscosity at
# 25 degC in mPa s. Used only to scale the tracer diffusion coefficients.
VISCOS_0_25 = 0.8900239182946

TC_MAX = 200.0          # transport.cpp caps tc for the viscosity model


# ============================================================================
# Parameter parsing
# ============================================================================

# ----------------------------------------------------------------------------
# PARAMETER SOURCE, and the one way the port differs from the research code.
# This repo's module parses PHREEQC's `pitzer.dat` on every call, which is right
# there because the file is the arbiter. A pip-installed library cannot: the
# user has no PHREEQC. The numbers are therefore EMBEDDED in
# `_lib_pitzer_params.py`, generated by brine_props/code/export_pitzer_params.py
# and verified bit-identical to a live parse. Passing `database=` raises rather
# than silently reading a file that is probably absent.
# ----------------------------------------------------------------------------

_JD_TABLE = {sp: {"jd": list(jd)} for sp, jd in JD.items()}
for _sp, (_dw, _dwt) in DW.items():
    _JD_TABLE.setdefault(_sp, {})["dw"] = _dw
    _JD_TABLE[_sp]["dw_t"] = _dwt


def load_parameters(database=None):
    """The embedded `pitzer.dat` table. See the note above on `database=`."""
    if database is not None:
        raise ValueError(
            "database= is not supported in pyResToolbox: the pitzer.dat "
            "parameters are embedded (see _lib_pitzer_params.py, generated by "
            "brine_props/code/export_pitzer_params.py). Re-export that table "
            "instead of pointing at a file.")
    return _JD_TABLE


def viscosity_parameters(database=None):
    return load_parameters(database)


# ============================================================================
# The model
# ============================================================================

def mu_water(T_K, P_MPa):
    """Pure-water viscosity in mPa s - IAPWS-2008, as PHREEQC uses."""
    return mu_iapws2008(T_K, rho_if97(T_K, P_MPa)) * 1e3


def _B_and_D(jd, tc, m_i, I, z):
    """The B*m and D*m terms for one ion, transport.cpp lines 6183-6195."""
    b0, b1, b2, d1, d2, d3 = jd[0], jd[1], jd[2], jd[3], jd[4], jd[5]

    # optional: values found at 25 degC held in slots 7, 8
    if jd[7] or jd[8]:
        b0 = jd[7] - b1 * math.exp(-b2 * 25.0)
        d1 = jd[8] / math.exp(-d2 * 25.0)

    B_term = (b0 + b1 * math.exp(-b2 * tc)) * m_i

    az = abs(z)
    f_z = (az * az + az) / 2.0 if az else (I / m_i)

    if d3 >= 1.0:
        fI = I / 3.0 / d3
    elif d3 > 0.4:
        fI = -0.8 / d3
    else:
        fI = -1.0

    D_term = ((d1 * math.exp(-d2 * tc)) * m_i
              * (I ** d3 * (1.0 + fI) + (m_i * f_z) ** d3) / (2.0 + fI))
    if D_term < -1e-5:
        D_term = 0.0
    return B_term, D_term


def _falkenhagen_dole_A(T_K, P_MPa, composition, params, mu_0):
    """
    The electrostatic term, returned already multiplied by mu_0 (mPa s), so
    that mu = mu_0 + A*sqrt(equivalents/2) as in transport.cpp.
    """
    eps_r = dielectric_constant(T_K, P_MPa * 10.0)
    scale = VISCOS_0_25 / mu_0

    m_plus = m_min = eq_plus = eq_min = eq_dw_plus = eq_dw_min = 0.0
    for sp, m_i in composition.items():
        z = CHARGE.get(sp, 0)
        if not z or m_i <= 0.0:
            continue
        rec = params.get(sp, {})
        Dw = rec.get('dw', 0.0)
        if not Dw:
            continue
        Dw *= scale
        dw_t = rec.get('dw_t', 0.0)
        if dw_t:
            Dw *= math.exp(dw_t / T_K - dw_t / 298.15)
        eq = m_i * abs(z)
        if z < 0:
            m_min += m_i
            eq_min += eq
            eq_dw_min += eq / Dw
        else:
            m_plus += m_i
            eq_plus += eq
            eq_dw_plus += eq / Dw

    if not (m_plus and m_min and eq_dw_plus and eq_dw_min):
        return 0.0

    z1, z2 = eq_plus / m_plus, eq_min / m_min
    D1, D2 = eq_plus / eq_dw_plus, eq_min / eq_dw_min

    t1 = ((D1 - D2)
          / (math.sqrt(D1 * z1 + D2 * z2) + math.sqrt((D1 + D2) * (z1 + z2))))
    psi = (D1 * z2 + D2 * z1) / 4.0 - z1 * z2 * t1 * t1
    A = (4.3787e-14 * T_K ** 1.5
         / (math.sqrt(eps_r * (z1 + z2) / max(z1, z2)) * (D1 * D2)) * psi)
    return A * math.sqrt((eq_plus + eq_min) / 2.0)


def _anion_factor(T_K, P_MPa, composition, params, I):
    """fan = 2 - V_an/V_Cl-, averaged over anions weighted by their molality."""
    P_bar = P_MPa * 10.0
    vm = parameters()
    V_an = m_an = 0.0
    V_Cl = None

    for sp, m_i in composition.items():
        if m_i <= 0.0:
            continue
        z = CHARGE.get(sp, 0)
        if z > 0:
            continue
        tan = params.get(sp, {}).get('jd', [0.0] * 10)[6]
        if sp == 'Cl-':
            V_Cl = Vm_ion('Cl-', T_K, P_bar, I, vm)
            V_an += V_Cl * m_i
            m_an += m_i
        elif tan and sp in vm:
            V_an += Vm_ion(sp, T_K, P_bar, I, vm) * tan * m_i
            m_an += m_i

    if not m_an:
        return 1.0
    if V_Cl is None:
        V_Cl = Vm_ion('Cl-', T_K, P_bar, I, vm)
    if not V_Cl:
        return 1.0
    return 2.0 - (V_an / m_an) / V_Cl


def viscosity_ratio(T_K, P_MPa, composition, database=None):
    """
    mu(solution)/mu(pure water) at the same T and P.

    composition: {ion: molality}, e.g. {'Na+': 3.0, 'Cl-': 3.0} or
                 {'Na+': 1.0, 'Ca+2': 1.0, 'Cl-': 3.0}.
    """
    params = viscosity_parameters(database)
    tc = min(T_K - 273.15, TC_MAX)
    I = ionic_strength(composition)
    mu_0 = mu_water(T_K, P_MPa)

    Bc = Dc = 0.0
    for sp, m_i in composition.items():
        if m_i <= 1e-9:
            continue
        if sp not in params or 'jd' not in params[sp]:
            # RAISE rather than silently contribute nothing - the same rule
            # salt_route follows for the volume leg. An ion with no
            # parameterisation is a gap in the model, not a zero.
            raise ValueError(
                f"{sp!r} carries no -viscosity parameters in pitzer.dat, so "
                f"this leg cannot represent it. Parameterised: "
                f"{', '.join(sorted(s for s, v in params.items() if 'jd' in v))}")
        jd = params[sp]['jd']
        if not (jd[0] or jd[1] or jd[3]):
            continue                      # Cl-, the reference solute (B = 0)
        B_term, D_term = _B_and_D(jd, tc, m_i, I, CHARGE.get(sp, 0))
        Bc += B_term
        Dc += D_term
    if Dc < 0.0:
        Dc = 0.0

    A_term = _falkenhagen_dole_A(T_K, P_MPa, composition, params, mu_0)
    fan = _anion_factor(T_K, P_MPa, composition, params, I)

    return 1.0 + A_term / mu_0 + fan * (Bc + Dc)


def brine_viscosity(T_K, P_MPa, composition, database=None):
    """Gas-free brine viscosity in mPa s (== cP)."""
    return mu_water(T_K, P_MPa) * viscosity_ratio(T_K, P_MPa, composition,
                                                  database)


def nacl_ratio(T_K, P_MPa, m):
    """Salt viscosity ratio for a pure NaCl brine of molality m."""
    if m <= 0.0:
        return 1.0
    return viscosity_ratio(T_K, P_MPa, {'Na+': m, 'Cl-': m})
